In [1]:
print("hello world");

hello world

In [2]:
import numpy as np
a = np.array([20,30,50,78]);
b = np.array([2,4,56,80]);
print("Additon", a+b);
print("Subtraction", a-b);
m = np.mean(a);
print("Mean of a :", m);
n = np.median(b);
print("Median of b :", n);
k = np.average(a);
print("Average of a :", k)

Additon [ 22  34 106 158]
Subtraction [18 26 -6 -2]
Mean of a : 44.5
Median of b : 30.0
Average of a : 44.5

In [3]:
a.size

4

In [4]:
marks_2d = np.array([
    [78,87,90],
    [23,20,29],
     [20, 56, 72]
])
print("Dimensions: ", marks_2d.ndim)
print("Shape: ", marks_2d.shape)

Dimensions:  2
Shape:  (3, 3)

In [5]:
#lect 2 23/sep/2026
import numpy as np
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr_2d[1,1]
arr_2d[0,:]#specific row
arr_2d[:,1] #specific column

array([2, 5, 8])

In [6]:
#pandas
import pandas as pd
#linear data called as series
#2D = data frame
#pandas is a python lib to handle tabular data.
url = "https://huggingface.co/datasets/prithivMLmods/Airbnb-Data-Map-Nyc/resolve/main/AB_NYC_2019.csv"
df = pd.read_csv(url)
print("Data loaded successfully !")

Data loaded successfully !

In [7]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [8]:
df.shape

(48895, 16)

In [9]:
df.tail(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [10]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [11]:
df.head(244)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,60794,"Bright and spacious, garden below!",293394,Rachel,Manhattan,Upper West Side,40.80021,-73.96071,Entire home/apt,195,4,4,2017-08-25,0.04,1,0
240,60948,ACCOMMODATIONS GALORE #2,126607,Laurine,Manhattan,East Harlem,40.80942,-73.93936,Entire home/apt,140,3,135,2019-06-20,1.30,3,192
241,61167,Colorful Private One Bedroom Apt,295760,Greta,Manhattan,Little Italy,40.71961,-73.99540,Entire home/apt,135,2,21,2015-12-12,0.20,1,0
242,61224,Huge Chelsea Loft,291112,Frank,Manhattan,Chelsea,40.74358,-74.00027,Entire home/apt,500,2,35,2017-07-27,0.34,1,348
243,61406,Great room in great location,297176,Bethania,Manhattan,Harlem,40.80335,-73.95750,Private room,80,14,10,2019-06-01,2.21,2,0

In [12]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [14]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [15]:
#Basic statistics
print("Mean : ",df["price"].mean())
print("Median : ",df["price"].median())
print("Average : ",df["price"].average())

Mean :  152.7206871868289
Median :  106.0

AttributeError: 'Series' object has no attribute 'average'

In [ ]:
df.isnull().sum()
#Missing percentage
print(df.isnull().mean()*100)

In [ ]:
print("Room Types")
print(df["room_type"].unique())

In [ ]:
print("Numbers of listing by room types")
print(df["room_type"].value_counts())

In [ ]:
# 240Sep2026

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imdevskp/corona-virus-report")

print("Path to dataset files:", path)

In [ ]:
import os
print(os.listdir(path))

In [ ]:
import pandas as pd
file_path = os.path.join(path, "covid_19_clean_complete.csv")
df = pd.read_csv(file_path)

In [ ]:
df.head(3)

In [ ]:
#Understand the Dataset
print("Shape :", df.shape)
print("Columns :", df.columns)
print("Data Type :", df.dtypes)

In [ ]:
df.isnull().sum()

In [ ]:
#check duplicate
df.duplicated().sum()